---
- name: COMMON - install common tools
  yum:
    name:
      - htop
      - vim
      - mc
      - lsof
      - wget
      - zip
      - unzip
      - nano
    enablerepo: "remi"
    state: present